### ISSUE TITLE
Affected Scenario: 28 - Incorrect monster icons used

### ISSUE THREAD

**Issue by Gritchu** [PurpleKingdomGames/virtual-gloomhaven-board#63]
**Affected Scenario(s):** 28 Outer Ritual Chamber

**Describe the bug**
The Virtual Gameboard uses an incorrect monster icon. In the top room, there should be three Night Demon monsters. The Virtual Gameboard shows three Living Spirits instead. Living Spirits aren't actually in this scenario.

**To Reproduce**
1. Go to 'Scenario 28'
2. Click on 'the top door with the open door tool selected to reveal the next room'
3. See error (compare to official scenario book)

**Browser :** [Chrome]

**Comment by hobnob** [comment]
Hi @Gritchu , sorry for the late reply on this - I'm hoping to get a fix for this into the next release, so it should be fixed in the next few weeks. This is much later than I'd normally want to fix a bug like this, but lots of things have come together to make releases a bit difficult at the moment... sorry for the delay :-/
