### ISSUE TITLE
Forgotten Circles 100 Won't Load

### ISSUE THREAD

**Issue by D1441** [PurpleKingdomGames/virtual-gloomhaven-board#80]
**Affected Scenario(s):** 100

**Describe the bug**
Try to change to scenario, but nothing changes.

**To Reproduce**
1. Click on Menu
2. Select Change Scenario
3. Set to 100
4. Click Ok
5. Error: nothing happens

**Browser :** [e.g. Chrome, Firefox]
Safari 14.1.2 (16622.3.10.1.6)

**Comment by hobnob** [comment]
Hi @D1441 , thanks for raising this issue. It's a known problem I'm afraid (see #71 ) 🙁 

The trouble with scenario 100 is that it's so complicated that it'll take quite a bit of work to get it working in the app. I am thinking of how to implement it though, so it will be fixed in a release in the future... I just don't know when yet.

I'll close this issue for now in favour of keeping #71 the single issue for this problem
